# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = leonardo
MONITOR_PORT = /dev/ttyACM0
ARDUINO_DIR  = /usr/share/arduino-1.6.5
include ~/code/Arduino-Makefile/Arduino.mk
